mysite/food/urls.py
from . import views
from django.urls import path
app_name = 'food'
urlpatterns = [
    path('',views.IndexClassView.as_view(), name ='index'),
    path('item/',views.item,name='item'),
    path('item/saveditem/',views.saveditem,name ="saveditem"),
    path('<int:pk>/',views.FoodDetail.as_view(),name ="detail"),
    path('add',views.CreateItem.as_view(),name='add_item'),
    path('edit/<int:id>/',views.edit_item,name="edit_item"),
    path('delete/<int:id>/',views.delete_item,name="delete_item"),
]

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default =1)
    item_name = models.CharField(max_length = 200)
    item_desc = models.CharField(max_length = 200)
    item_price = models.IntegerField()
    item_img = models.CharField(max_length=1000,default ="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRftcWMZycPdTp4H5yYhp9SroBMfuVYJLLPDIQ4JvLRpSSHhnwIwPKmeNXeBlKRY88p8C8&usqp=CAU")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_img']

mysite/food/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Item
from django.template import loader
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
from .forms import ItemForm
def index(request):
    items = Item.objects.all()
    template = loader.get_template('food/index.html')
    context = {
        'item_list':items,
    }
    # return HttpResponse(template.render(context,request))
    return render(request,'food/index.html',context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


def item(request):
    return HttpResponse('This is an item View')

def saveditem(request):
    return HttpResponse("<h1>These are your saved item</h1>")

def detail(request, item_id):
    item = Item.objects.get(id=item_id)
    context ={
        'item':item,
    }
    # return HttpResponse("Item Details " % item)
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = "food/detail.html"


def add_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})


# class based view for create item
class CreateItem(CreateView):
    model = Item;
    fields = ['item_name','item_desc','item_price','item_img']
    template_name = 'food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)    

def edit_item(request,id):
    item = Item.objects.get(id = id)
    form = ItemForm(request.POST or None, instance = item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

def delete_item(request,id):
    item = Item.objects.get(id = id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>

        <div class="navbar">
            <a href="{% url 'food:add_item' %}" class="nav-item nav-link">Add Item</a>
            <a href="#" class="nav-item nav-link">Delete Item</a>
            <a href="#" class="nav-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-item nav-link">Logout</a>
                <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-{{msg.tags}}"> 
            {{ msg }}
        </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_img}}" alt="" class="card">
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h3>Rs {{object.item_price}}</h3>
            <a href="{% url 'food:delete_item' object.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <title>Document</title>
    </head>
<body>
    {% block body %}
    <!-- <h1>Items Available</h1>
    <ul>
        {% for item in item_list %}
            <li><a href="{% url 'food:detail' item.id %}">{{ item.id }} -- {{  item.item_name }}</li></a>
        {% endfor %}
    </ul> -->

    {% for item in item_list %}
    <div class="row">
        <div class="col-md-3-md-2 offset-md-2">
            <img src="{{ item.item_img }}" alt="" class="card" height="150px" width="150px">
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>Rs {{item.item_price}}</h6>
            <h6>{{item.user_name}}</h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

        </div>
    </div>
    {% endfor %}
    {% endblock %}
    
</body>
</html>

mysite/food/templates/food/item-delete.html
<form action="" method="post">
    {% csrf_token %}
    <h2>Are you sure want to delete {{item.item_name}}</h2>
    <button type="submit">Confirm</button>
</form>

mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <div class="card-title">Add Item</div>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button class="btn-info"type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}